trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Create a zip package
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'demojuly23'
    appName: 'demotoday'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
